"""schema inicial

Revision ID: 1ea62d17932e
Revises: 
Create Date: 2026-09-30 19:34:57.009943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ea62d17932e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('actor_user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_audit_org_occurred', ['organization_id', 'occurred_at'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('timezone', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_table('client_types',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_client_types_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_types'))
    )
    with op.batch_alter_table('client_types', schema=None) as batch_op:
        batch_op.create_index('ix_client_types_org_slug', ['organization_id', 'slug'], unique=True)

    op.create_table('holidays',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_holidays_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holidays'))
    )
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.create_index('ix_holidays_org_date', ['organization_id', 'date'], unique=True)

    op.create_table('insurers',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_insurers_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insurers'))
    )
    with op.batch_alter_table('insurers', schema=None) as batch_op:
        batch_op.create_index('ix_insurers_org_name', ['organization_id', 'name'], unique=True)

    op.create_table('loss_reasons',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_loss_reasons_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loss_reasons'))
    )
    with op.batch_alter_table('loss_reasons', schema=None) as batch_op:
        batch_op.create_index('ix_loss_reasons_org_slug', ['organization_id', 'slug'], unique=True)

    op.create_table('next_action_types',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_next_action_types_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_next_action_types'))
    )
    with op.batch_alter_table('next_action_types', schema=None) as batch_op:
        batch_op.create_index('ix_next_action_types_org_slug', ['organization_id', 'slug'], unique=True)

    op.create_table('origins',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_origins_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_origins'))
    )
    with op.batch_alter_table('origins', schema=None) as batch_op:
        batch_op.create_index('ix_origins_org_slug', ['organization_id', 'slug'], unique=True)

    op.create_table('products',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_products_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('ix_products_org_slug', ['organization_id', 'slug'], unique=True)

    op.create_table('tag_categories',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_tag_categories_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag_categories'))
    )
    with op.batch_alter_table('tag_categories', schema=None) as batch_op:
        batch_op.create_index('ix_tag_categories_org_slug', ['organization_id', 'slug'], unique=True)

    op.create_table('teams',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_teams_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_org_email', ['organization_id', 'email'], unique=True)

    op.create_table('absences',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('substitute_user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_absences_organization_id_organizations')),
    sa.ForeignKeyConstraint(['substitute_user_id'], ['users.id'], name=op.f('fk_absences_substitute_user_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_absences_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_absences'))
    )
    with op.batch_alter_table('absences', schema=None) as batch_op:
        batch_op.create_index('ix_absences_user_period', ['user_id', 'starts_on'], unique=False)

    op.create_table('bonus_rules',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('product_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('base', sa.String(length=20), nullable=False),
    sa.Column('bracket_min', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bracket_max', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('bonus_kind', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_bonus_rules_organization_id_organizations')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_bonus_rules_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bonus_rules'))
    )
    with op.batch_alter_table('bonus_rules', schema=None) as batch_op:
        batch_op.create_index('ix_bonus_rules_product_base', ['product_id', 'base'], unique=False)

    op.create_table('cross_sell_lists',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target_product_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('released_items', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_cross_sell_lists_created_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_cross_sell_lists_organization_id_organizations')),
    sa.ForeignKeyConstraint(['target_product_id'], ['products.id'], name=op.f('fk_cross_sell_lists_target_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cross_sell_lists'))
    )
    with op.batch_alter_table('cross_sell_lists', schema=None) as batch_op:
        batch_op.create_index('ix_cross_sell_lists_org_state', ['organization_id', 'state'], unique=False)

    op.create_table('daily_prospecting_quotas',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('quota', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_daily_prospecting_quotas_organization_id_organizations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_prospecting_quotas_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_prospecting_quotas'))
    )
    with op.batch_alter_table('daily_prospecting_quotas', schema=None) as batch_op:
        batch_op.create_index('ix_dpq_user_effective', ['user_id', 'effective_from'], unique=False)

    op.create_table('funnels',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('product_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_funnels_organization_id_organizations')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_funnels_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_funnels'))
    )
    with op.batch_alter_table('funnels', schema=None) as batch_op:
        batch_op.create_index('ix_funnels_org_product', ['organization_id', 'product_id'], unique=False)

    op.create_table('import_batches',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_ok', sa.Integer(), nullable=False),
    sa.Column('rows_error', sa.Integer(), nullable=False),
    sa.Column('rows_duplicate', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_import_batches_created_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_import_batches_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches'))
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index('ix_import_batches_org_created', ['organization_id', 'created_at'], unique=False)

    op.create_table('leads',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('kind', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('document', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.CHAR(length=2), nullable=True),
    sa.Column('indicator_name', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('origin_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('client_type_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_type_id'], ['client_types.id'], name=op.f('fk_leads_client_type_id_client_types')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_leads_created_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_leads_organization_id_organizations')),
    sa.ForeignKeyConstraint(['origin_id'], ['origins.id'], name=op.f('fk_leads_origin_id_origins')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads'))
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index('ix_leads_org_name', ['organization_id', 'name'], unique=False)
        batch_op.create_index('ix_leads_org_state_city', ['organization_id', 'state', 'city'], unique=False)

    op.create_table('monthly_goals',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('product_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('target_net_premium', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_monthly_goals_organization_id_organizations')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_monthly_goals_product_id_products')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_monthly_goals_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monthly_goals')),
    sa.UniqueConstraint('organization_id', 'user_id', 'product_id', 'year', 'month', name='uq_monthly_goals_scope')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=True),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.String(length=40), nullable=True),
    sa.Column('link_path', sa.String(length=200), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dedup_key', sa.String(length=200), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_notifications_organization_id_organizations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('organization_id', 'user_id', 'dedup_key', name='uq_notifications_dedup')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_user_read', ['user_id', 'read_at'], unique=False)

    op.create_table('permission_grants',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('granted_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('target_user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('permission', sa.String(length=80), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name=op.f('fk_permission_grants_granted_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_permission_grants_organization_id_organizations')),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], name=op.f('fk_permission_grants_target_user_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_permission_grants_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permission_grants'))
    )
    with op.batch_alter_table('permission_grants', schema=None) as batch_op:
        batch_op.create_index('ix_permission_grants_user_perm', ['user_id', 'permission'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('category_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tag_categories.id'], name=op.f('fk_tags_category_id_tag_categories')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_tags_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index('ix_tags_org_name', ['organization_id', 'name'], unique=True)

    op.create_table('user_products',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('product_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_user_products_product_id_products')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_products_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'product_id', name=op.f('pk_user_products'))
    )
    op.create_table('availabilities',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lead_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('product_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('team_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('origin_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('released_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claimed_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['claimed_by'], ['users.id'], name=op.f('fk_availabilities_claimed_by_users')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_availabilities_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_availabilities_organization_id_organizations')),
    sa.ForeignKeyConstraint(['origin_id'], ['origins.id'], name=op.f('fk_availabilities_origin_id_origins')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_availabilities_product_id_products')),
    sa.ForeignKeyConstraint(['released_by'], ['users.id'], name=op.f('fk_availabilities_released_by_users')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_availabilities_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availabilities'))
    )
    with op.batch_alter_table('availabilities', schema=None) as batch_op:
        batch_op.create_index('ix_availabilities_open', ['organization_id', 'product_id', 'lead_id'], unique=False)

    op.create_table('bonus_payments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('product_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('predicted_on', sa.Date(), nullable=False),
    sa.Column('metric_base', sa.String(length=20), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('applied_rule_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('applied_rule_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applied_rule_id'], ['bonus_rules.id'], name=op.f('fk_bonus_payments_applied_rule_id_bonus_rules')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_bonus_payments_approved_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_bonus_payments_organization_id_organizations')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_bonus_payments_product_id_products')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bonus_payments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bonus_payments')),
    sa.UniqueConstraint('organization_id', 'user_id', 'product_id', 'year', 'month', name='uq_bonus_payments_scope')
    )
    op.create_table('funnel_stages',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('funnel_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_initial', sa.Boolean(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['funnel_id'], ['funnels.id'], name=op.f('fk_funnel_stages_funnel_id_funnels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_funnel_stages_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_funnel_stages'))
    )
    with op.batch_alter_table('funnel_stages', schema=None) as batch_op:
        batch_op.create_index('ix_funnel_stages_funnel_order', ['funnel_id', 'order_index'], unique=False)

    op.create_table('import_rows',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('batch_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('duplicate_of_lead_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_import_rows_batch_id_import_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['duplicate_of_lead_id'], ['leads.id'], name=op.f('fk_import_rows_duplicate_of_lead_id_leads')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_import_rows_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_rows'))
    )
    with op.batch_alter_table('import_rows', schema=None) as batch_op:
        batch_op.create_index('ix_import_rows_batch_status', ['batch_id', 'status'], unique=False)

    op.create_table('lead_phones',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lead_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('phone_e164', sa.String(length=20), nullable=False),
    sa.Column('original', sa.String(length=40), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_lead_phones_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_lead_phones_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_phones'))
    )
    with op.batch_alter_table('lead_phones', schema=None) as batch_op:
        batch_op.create_index('ix_lead_phones_lead', ['lead_id'], unique=False)
        batch_op.create_index('ix_lead_phones_org_phone', ['organization_id', 'phone_e164'], unique=True)

    op.create_table('lead_products',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lead_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('product_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('known_since', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_lead_products_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_lead_products_organization_id_organizations')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_lead_products_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_products'))
    )
    with op.batch_alter_table('lead_products', schema=None) as batch_op:
        batch_op.create_index('ix_lead_products_unique', ['organization_id', 'lead_id', 'product_id'], unique=True)

    op.create_table('lead_tags',
    sa.Column('lead_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tag_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_lead_tags_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_lead_tags_organization_id_organizations')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_lead_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lead_id', 'tag_id', name=op.f('pk_lead_tags'))
    )
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lead_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('plate', sa.String(length=10), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_vehicles_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_vehicles_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles'))
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index('ix_vehicles_org_plate', ['organization_id', 'plate'], unique=False)

    op.create_table('cross_sell_items',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('list_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lead_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('availability_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['availability_id'], ['availabilities.id'], name=op.f('fk_cross_sell_items_availability_id_availabilities')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_cross_sell_items_lead_id_leads')),
    sa.ForeignKeyConstraint(['list_id'], ['cross_sell_lists.id'], name=op.f('fk_cross_sell_items_list_id_cross_sell_lists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_cross_sell_items_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cross_sell_items'))
    )
    with op.batch_alter_table('cross_sell_items', schema=None) as batch_op:
        batch_op.create_index('ix_cross_sell_items_list_state', ['list_id', 'state'], unique=False)

    op.create_table('schedules',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lead_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('product_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('owner_user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('coverage_end_date', sa.Date(), nullable=False),
    sa.Column('date_confirmed', sa.Boolean(), nullable=False),
    sa.Column('insurer_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('vehicle_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('origin_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_reason', sa.Text(), nullable=True),
    sa.Column('previous_schedule_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('contacted_opportunity_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contacted_opportunity_id'], ['opportunities.id'], name=op.f('fk_schedules_contacted_opportunity_id_opportunities'), use_alter=True),
    sa.ForeignKeyConstraint(['insurer_id'], ['insurers.id'], name=op.f('fk_schedules_insurer_id_insurers')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_schedules_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_schedules_organization_id_organizations')),
    sa.ForeignKeyConstraint(['origin_id'], ['origins.id'], name=op.f('fk_schedules_origin_id_origins')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_schedules_owner_user_id_users')),
    sa.ForeignKeyConstraint(['previous_schedule_id'], ['schedules.id'], name=op.f('fk_schedules_previous_schedule_id_schedules')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_schedules_product_id_products')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_schedules_vehicle_id_vehicles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules'))
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index('ix_schedules_org_coverage', ['organization_id', 'coverage_end_date'], unique=False)
        batch_op.create_index('ix_schedules_owner_state', ['owner_user_id', 'state'], unique=False)

    op.create_table('opportunities',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lead_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('product_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('funnel_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('current_stage_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('owner_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('origin', sa.String(length=80), nullable=True),
    sa.Column('source_availability_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('source_schedule_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_relevant_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('loss_reason_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('loss_justification', sa.String(length=2000), nullable=True),
    sa.Column('recycled_to_schedule_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['current_stage_id'], ['funnel_stages.id'], name=op.f('fk_opportunities_current_stage_id_funnel_stages')),
    sa.ForeignKeyConstraint(['funnel_id'], ['funnels.id'], name=op.f('fk_opportunities_funnel_id_funnels')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_opportunities_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loss_reason_id'], ['loss_reasons.id'], name=op.f('fk_opportunities_loss_reason_id_loss_reasons')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_opportunities_organization_id_organizations')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_opportunities_owner_user_id_users')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_opportunities_product_id_products')),
    sa.ForeignKeyConstraint(['recycled_to_schedule_id'], ['schedules.id'], name=op.f('fk_opportunities_recycled_to_schedule_id_schedules')),
    sa.ForeignKeyConstraint(['source_availability_id'], ['availabilities.id'], name=op.f('fk_opportunities_source_availability_id_availabilities')),
    sa.ForeignKeyConstraint(['source_schedule_id'], ['schedules.id'], name=op.f('fk_opportunities_source_schedule_id_schedules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunities'))
    )
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.create_index('ix_opportunities_org_state', ['organization_id', 'state'], unique=False)
        batch_op.create_index('ix_opportunities_owner_state', ['owner_user_id', 'state'], unique=False)
        batch_op.create_index('uq_opportunities_open_unique', ['organization_id', 'lead_id', 'product_id'], unique=True, postgresql_where=sa.text("state = 'open'"))

    op.create_table('activities',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('opportunity_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('lead_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('schedule_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actor_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('beneficiary_user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('counts_for_daily_metric', sa.String(length=40), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_activities_actor_user_id_users')),
    sa.ForeignKeyConstraint(['beneficiary_user_id'], ['users.id'], name=op.f('fk_activities_beneficiary_user_id_users')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_activities_lead_id_leads')),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_activities_opportunity_id_opportunities')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_activities_organization_id_organizations')),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('fk_activities_schedule_id_schedules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities')),
    sa.UniqueConstraint('organization_id', 'idempotency_key', name='uq_activities_idempotency')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index('ix_activities_actor_occurred', ['actor_user_id', 'occurred_at'], unique=False)
        batch_op.create_index('ix_activities_metric', ['counts_for_daily_metric'], unique=False)
        batch_op.create_index('ix_activities_opportunity', ['opportunity_id', 'occurred_at'], unique=False)

    op.create_table('sales',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lead_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('opportunity_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('product_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('seller_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('insurer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('client_type_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('net_premium', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('commission_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('closed_on', sa.Date(), nullable=False),
    sa.Column('origin', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edit_deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_reason', sa.String(length=500), nullable=True),
    sa.Column('cancelled_kind', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_type_id'], ['client_types.id'], name=op.f('fk_sales_client_type_id_client_types')),
    sa.ForeignKeyConstraint(['insurer_id'], ['insurers.id'], name=op.f('fk_sales_insurer_id_insurers')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_sales_lead_id_leads')),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_sales_opportunity_id_opportunities')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_sales_organization_id_organizations')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_sales_product_id_products')),
    sa.ForeignKeyConstraint(['seller_user_id'], ['users.id'], name=op.f('fk_sales_seller_user_id_users')),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], name=op.f('fk_sales_validated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales'))
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index('ix_sales_org_closed_state', ['organization_id', 'closed_on', 'state'], unique=False)
        batch_op.create_index('ix_sales_seller_closed', ['seller_user_id', 'closed_on'], unique=False)

    op.create_table('next_actions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('opportunity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('generation_key', sa.String(length=120), nullable=True),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('done_activity_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['done_activity_id'], ['activities.id'], name=op.f('fk_next_actions_done_activity_id_activities')),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_next_actions_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_next_actions_organization_id_organizations')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_next_actions_owner_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_next_actions')),
    sa.UniqueConstraint('organization_id', 'generation_key', name='uq_next_actions_generation')
    )
    with op.batch_alter_table('next_actions', schema=None) as batch_op:
        batch_op.create_index('ix_next_actions_owner_state_due', ['owner_user_id', 'state', 'due_at'], unique=False)

    op.create_table('sale_revisions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sale_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('submitted_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_sale_revisions_organization_id_organizations')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_sale_revisions_reviewed_by_users')),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name=op.f('fk_sale_revisions_sale_id_sales'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('fk_sale_revisions_submitted_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sale_revisions'))
    )
    with op.batch_alter_table('sale_revisions', schema=None) as batch_op:
        batch_op.create_index('ix_sale_revisions_sale_state', ['sale_id', 'state'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_revisions', schema=None) as batch_op:
        batch_op.drop_index('ix_sale_revisions_sale_state')

    op.drop_table('sale_revisions')
    with op.batch_alter_table('next_actions', schema=None) as batch_op:
        batch_op.drop_index('ix_next_actions_owner_state_due')

    op.drop_table('next_actions')
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index('ix_sales_seller_closed')
        batch_op.drop_index('ix_sales_org_closed_state')

    op.drop_table('sales')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index('ix_activities_opportunity')
        batch_op.drop_index('ix_activities_metric')
        batch_op.drop_index('ix_activities_actor_occurred')

    op.drop_table('activities')
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_index('uq_opportunities_open_unique', postgresql_where=sa.text("state = 'open'"))
        batch_op.drop_index('ix_opportunities_owner_state')
        batch_op.drop_index('ix_opportunities_org_state')

    op.drop_table('opportunities')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index('ix_schedules_owner_state')
        batch_op.drop_index('ix_schedules_org_coverage')

    op.drop_table('schedules')
    with op.batch_alter_table('cross_sell_items', schema=None) as batch_op:
        batch_op.drop_index('ix_cross_sell_items_list_state')

    op.drop_table('cross_sell_items')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index('ix_vehicles_org_plate')

    op.drop_table('vehicles')
    op.drop_table('lead_tags')
    with op.batch_alter_table('lead_products', schema=None) as batch_op:
        batch_op.drop_index('ix_lead_products_unique')

    op.drop_table('lead_products')
    with op.batch_alter_table('lead_phones', schema=None) as batch_op:
        batch_op.drop_index('ix_lead_phones_org_phone')
        batch_op.drop_index('ix_lead_phones_lead')

    op.drop_table('lead_phones')
    with op.batch_alter_table('import_rows', schema=None) as batch_op:
        batch_op.drop_index('ix_import_rows_batch_status')

    op.drop_table('import_rows')
    with op.batch_alter_table('funnel_stages', schema=None) as batch_op:
        batch_op.drop_index('ix_funnel_stages_funnel_order')

    op.drop_table('funnel_stages')
    op.drop_table('bonus_payments')
    with op.batch_alter_table('availabilities', schema=None) as batch_op:
        batch_op.drop_index('ix_availabilities_open')

    op.drop_table('availabilities')
    op.drop_table('user_products')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index('ix_tags_org_name')

    op.drop_table('tags')
    with op.batch_alter_table('permission_grants', schema=None) as batch_op:
        batch_op.drop_index('ix_permission_grants_user_perm')

    op.drop_table('permission_grants')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_read')

    op.drop_table('notifications')
    op.drop_table('monthly_goals')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index('ix_leads_org_state_city')
        batch_op.drop_index('ix_leads_org_name')

    op.drop_table('leads')
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index('ix_import_batches_org_created')

    op.drop_table('import_batches')
    with op.batch_alter_table('funnels', schema=None) as batch_op:
        batch_op.drop_index('ix_funnels_org_product')

    op.drop_table('funnels')
    with op.batch_alter_table('daily_prospecting_quotas', schema=None) as batch_op:
        batch_op.drop_index('ix_dpq_user_effective')

    op.drop_table('daily_prospecting_quotas')
    with op.batch_alter_table('cross_sell_lists', schema=None) as batch_op:
        batch_op.drop_index('ix_cross_sell_lists_org_state')

    op.drop_table('cross_sell_lists')
    with op.batch_alter_table('bonus_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_bonus_rules_product_base')

    op.drop_table('bonus_rules')
    with op.batch_alter_table('absences', schema=None) as batch_op:
        batch_op.drop_index('ix_absences_user_period')

    op.drop_table('absences')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_org_email')

    op.drop_table('users')
    op.drop_table('teams')
    with op.batch_alter_table('tag_categories', schema=None) as batch_op:
        batch_op.drop_index('ix_tag_categories_org_slug')

    op.drop_table('tag_categories')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_org_slug')

    op.drop_table('products')
    with op.batch_alter_table('origins', schema=None) as batch_op:
        batch_op.drop_index('ix_origins_org_slug')

    op.drop_table('origins')
    with op.batch_alter_table('next_action_types', schema=None) as batch_op:
        batch_op.drop_index('ix_next_action_types_org_slug')

    op.drop_table('next_action_types')
    with op.batch_alter_table('loss_reasons', schema=None) as batch_op:
        batch_op.drop_index('ix_loss_reasons_org_slug')

    op.drop_table('loss_reasons')
    with op.batch_alter_table('insurers', schema=None) as batch_op:
        batch_op.drop_index('ix_insurers_org_name')

    op.drop_table('insurers')
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.drop_index('ix_holidays_org_date')

    op.drop_table('holidays')
    with op.batch_alter_table('client_types', schema=None) as batch_op:
        batch_op.drop_index('ix_client_types_org_slug')

    op.drop_table('client_types')
    op.drop_table('organizations')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_org_occurred')
        batch_op.drop_index('ix_audit_entity')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
